In [ ]:
import torch 
import numpy as np 

: 

# Part 1 
- https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/0e6615c5a7bc71e01ff3c51217ea00da/tensorqs_tutorial.ipynb#scrollTo=FvdZH8m1R77X


### all the ways to create torch tensor 

In [16]:
small_tensor = [[1,7,4],[4,4,5]]
small_tensor = torch.tensor(small_tensor)
type(small_tensor)

torch.Tensor

In [11]:
np_array = np.random.rand(3,4)
np_array = torch.tensor(np_array)
type(np_array)

torch.Tensor

In [26]:
random_tensor = torch.rand(4,4)

In [ ]:
small_rand_tensor = torch.rand_like(small_tensor, dtype=torch.float)
small_one_tensor = torch.ones_like(small_tensor)
small_zero_tensor = torch.zeros_like(small_tensor)

print(f'{small_rand_tensor},\n {small_one_tensor},\n {small_zero_tensor}')


tensor([[0.0170, 0.8849, 0.0288],
        [0.7873, 0.7530, 0.5505]]),
 tensor([[1, 1, 1],
        [1, 1, 1]]),
 tensor([[0, 0, 0],
        [0, 0, 0]])


In [30]:
rand_tensor = torch.rand(2,5)
ones_tensor = torch.ones(2,3)
zeros_tensor = torch.zeros(3,5)
full_tensor = torch.full((4, 4), 61)
print(f'{rand_tensor},\n {ones_tensor},\n {zeros_tensor},\n {full_tensor}')


tensor([[0.9179, 0.4048, 0.5064, 0.6377, 0.4848],
        [0.2423, 0.2831, 0.4824, 0.2274, 0.5213]]),
 tensor([[1., 1., 1.],
        [1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 tensor([[61, 61, 61, 61],
        [61, 61, 61, 61],
        [61, 61, 61, 61],
        [61, 61, 61, 61]])


### Tensors slices like in nupy

In [ ]:
big_tensor = [[[[1,1,4],[4,5,6]],[[2,3,4],[8,8,9]]],
              [[[3,3,4],[1,5,1]],[[2,1,1],[0,0,9]]]]
big_tensor = torch.tensor(big_tensor)
print(big_tensor.shape)
baby_tensor1 = big_tensor[0,:,1,:]
baby_tansor2 = big_tensor[1,1,:,2]
print(f'{baby_tensor1}, \n{baby_tansor2}')


NameError: name 'torch' is not defined

In [63]:
print(baby_tensor1.dtype)
baby_tensor1 @ baby_tensor1.T
big_tensor.reshape(6,4)


torch.int64


tensor([[1, 1, 4, 4],
        [5, 6, 2, 3],
        [4, 8, 8, 9],
        [3, 3, 4, 1],
        [5, 1, 2, 1],
        [1, 0, 0, 9]])

### Checkind and choosing device 

In [58]:
if torch.cuda.is_available():
    print("CUDA (GPU) avellible! Shifting tensor opun GPU.")
    device = torch.device("cuda")
    tensor = baby_tensor1.to(device)
    print(f"Now tensor on : {tensor.device}")
    
else:
    print("GPU not avellible . Tensor stay opun CPU.")

GPU not avellible . Tensor stay opun CPU.


###  Operations that store the result into the operand are called in-place.

In [ ]:
big_tensor.add_(5)
baby_tansor2._t


# Part 2
- https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/ad7e62b138c384adac98888ce94ff659/autogradqs_tutorial.ipynb