In [3]:
import torch 
import numpy as np 

# Part 1 
- https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/0e6615c5a7bc71e01ff3c51217ea00da/tensorqs_tutorial.ipynb#scrollTo=FvdZH8m1R77X


### all the ways to create torch tensor 

In [4]:
small_tensor = [[1,7,4],[4,4,5]]
small_tensor = torch.tensor(small_tensor)
type(small_tensor)

torch.Tensor

In [5]:
np_array = np.random.rand(3,4)
np_array = torch.tensor(np_array)
type(np_array)

torch.Tensor

In [6]:
random_tensor = torch.rand(4,4)

In [7]:
small_rand_tensor = torch.rand_like(small_tensor, dtype=torch.float)
small_one_tensor = torch.ones_like(small_tensor)
small_zero_tensor = torch.zeros_like(small_tensor)

print(f'{small_rand_tensor},\n {small_one_tensor},\n {small_zero_tensor}')


tensor([[0.5106, 0.7587, 0.7180],
        [0.9986, 0.3072, 0.3774]]),
 tensor([[1, 1, 1],
        [1, 1, 1]]),
 tensor([[0, 0, 0],
        [0, 0, 0]])


In [8]:
rand_tensor = torch.rand(2,5)
ones_tensor = torch.ones(2,3)
zeros_tensor = torch.zeros(3,5)
full_tensor = torch.full((4, 4), 61)
print(f'{rand_tensor},\n {ones_tensor},\n {zeros_tensor},\n {full_tensor}')


tensor([[0.2528, 0.8961, 0.4835, 0.2887, 0.1666],
        [0.5243, 0.1026, 0.6463, 0.9793, 0.7873]]),
 tensor([[1., 1., 1.],
        [1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 tensor([[61, 61, 61, 61],
        [61, 61, 61, 61],
        [61, 61, 61, 61],
        [61, 61, 61, 61]])


### Tensors slices like in nupy

In [9]:
big_tensor = [[[[1,1,4],[4,5,6]],[[2,3,4],[8,8,9]]],
              [[[3,3,4],[1,5,1]],[[2,1,1],[0,0,9]]]]
big_tensor = torch.tensor(big_tensor)
print(big_tensor.shape)
baby_tensor1 = big_tensor[0,:,1,:]
baby_tansor2 = big_tensor[1,1,:,2]
print(f'{baby_tensor1}, \n{baby_tansor2}')


torch.Size([2, 2, 2, 3])
tensor([[4, 5, 6],
        [8, 8, 9]]), 
tensor([1, 9])


In [10]:
print(baby_tensor1.dtype)
baby_tensor1 @ baby_tensor1.T
big_tensor.reshape(6,4)


torch.int64


tensor([[1, 1, 4, 4],
        [5, 6, 2, 3],
        [4, 8, 8, 9],
        [3, 3, 4, 1],
        [5, 1, 2, 1],
        [1, 0, 0, 9]])

### Checkind and choosing device 

In [11]:
if torch.cuda.is_available():
    print("CUDA (GPU) avellible! Shifting tensor opun GPU.")
    device = torch.device("cuda")
    tensor = baby_tensor1.to(device)
    print(f"Now tensor on : {tensor.device}")
    
else:
    print("GPU not avellible . Tensor stay opun CPU.")

GPU not avellible . Tensor stay opun CPU.


###  Operations that store the result into the operand are called in-place.

In [23]:
big_tensor.add_(5)
baby_tansor2.t_()
print( baby_tansor2.add_(4))


tensor([9, 9])


# Part 2
- https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/ad7e62b138c384adac98888ce94ff659/autogradqs_tutorial.ipynb

In [ ]:
import torch.nn.functional as F
x = torch.tensor([[1.0,2.0],[1.0,2.0],[1.0,2.0]])
y = torch.tensor([[1.0,0.0,1.0],[0.0,1.0,0.0],[0.0,1.0,1.0]])
w = torch.randn(2,3 , requires_grad = True)
b = torch.randn(1,3 , requires_grad = True)
z = x @ w + b
p = torch.sigmoid(z) # задание ф-ии активации
loss = F.binary_cross_entropy(p, y) # задание ф-ии ошибки 

loss.backward()
print("prediction size z:", z.shape)
print("size y:", y.shape)
print("Loss:", loss.item())

prediction size z: torch.Size([3, 3])
size y: torch.Size([3, 3])
Loss: 1.0850567817687988


In [69]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x0000023C2854C3A0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000023C2854FD60>


Tern off  grad

In [89]:
print(z.requires_grad)
print(z.detach().requires_grad)

True
False
